version: "3.9"
services:
    mysql:
        image: mysql:latest
        container_name: lar1-db
        working_dir: /var/www/lar1
        volumes:
            - ./:/var/www/lar1
            - mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 0
        ports:
            - "${CUSTOM_DB_PORT:-3306}:3306"
        restart: unless-stopped

    nginx:
        image: nginx:stable-alpine
        container_name: lar1-nginx
        working_dir: /var/www/lar1
        volumes:
            - ./:/var/www/lar1
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${CUSTOM_NGINX_PORT:-80}:80"
        depends_on:
            - php
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                DOCKER_USER_ID: ${DOCKER_USER_ID}
                DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        container_name: lar1-php
        working_dir: /var/www/lar1
        volumes:
            - ./:/var/www/lar1
        depends_on:
            - mysql
        restart: unless-stopped

    node:
        build:
            context: .
            dockerfile: docker/node/Dockerfile
            args:
                DOCKER_USER_ID: ${DOCKER_USER_ID}
                DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
        container_name: lar1-node
        working_dir: /var/www/lar1
        volumes:
            - ./:/var/www/lar1
        restart: unless-stopped

networks:
    default:

volumes:
    mysql:
